#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

defaults: &defaults

  ######################################################
  # Environment Configuration
  ######################################################

  ## Set the hostname of the machine you're running Diaspora on, as seen
  ## from the internet. This should be the URL you want to use to
  ## access the pod. So if you plan to  reverse proxy it, it should be
  ## the URL the proxy listens on.
  ## DO NOT CHNANGE THIS AFTER INITIAL SETUP
  ## UNLESS YOU KNOW WHAT YOU'RE DOING!
  ## However changing http to https is okay and has no consquences.
  ## If you do change it you have to start over as it's hardcoded into
  ## the database.
  pod_url: "http://localhost:3000/"

  ## Setting the bundle of certificate authorities (CA) certificates.
  ## This is operating system specific.
  ## Examples, uncomment one or add your own:
  ca_file: '/etc/pki/tls/certs/ca-bundle.crt'

  ## Name of your pod
  pod_name: "Volontari.at*"

  ######################################################
  # Email Configuration
  ######################################################

  ## First you need to enable it ;)
  mailer_on: false

  ## Sender address used in mail send by Diaspora
  #sender_address: 'no-reply@example.org'

  ## This selects which mailer should be used. Take 'smtp' for a smtp
  ## connection, 'sendmail' to use the sendmail binary or
  ## 'messagebus' to use the messagebus service.
  mailer_method: 'smtp'

  # Address/port to smtp server handling outgoing mail.
  smtp_address: 'smtp.example.com'
  smtp_port: '587'

  #API key if you are using message bus
  message_bus_api_key: ''

  # The path to the sendmail binary. Ignored if mailer_method is not set to sendmail
  sendmail_location: '/usr/sbin/sendmail'

  # Set this to true if you want to use exim and sendmail
  sendmail_exim_fix: false

  # Authentication required to send mail. Use one of 'plain',
  # 'login' or 'cram_md5'. Use 'none' if server does not support
  # authentication
  smtp_authentication: 'plain'

  # Automatically enable TLS? Ignored if smtp_authentication is set to none
  smtp_starttls_auto: true

  # OpenSSL verify mode used when connecting to a SMTP server with TLS.
  # Set this to none if you have a self signed certificate, keep it empty (not '') for the default
  # Possible values: none, peer, client_once, fail_if_no_peer_cert
  smtp_openssl_verify_mode:

  # Domain of smtp server.
  # This should match the common name of the certificate
  # the SMTP server sends. If he sends one
  smtp_domain: 'example.com'

  # Credentials to log in to the SMTP server - may be necessary if
  # smtp_authentication is not 'none'
  smtp_username: 'smtp_username'
  smtp_password: 'secret'

  # Sender address in Diaspora's outgoing mail.
  smtp_sender_address: 'no-reply@volontari.at'

  ######################################################
  # Social Service Configuration
  ######################################################

  ## OAuth credentials for Facebook:
  facebook_app_id:  ''
  facebook_app_secret: ''

  #this will be the namespace for your object, it should be configured in your FB app
  open_graph_namespace: ''


  ## OAuth credentials for Twitter:
  twitter_consumer_key: ''
  twitter_consumer_secret: ''

  ## OAuth credentials for Tumblr
  tumblr_consumer_key: ''
  tumblr_consumer_secret: ''


  ######################################################
  # Debugging Service Tool Integration
  ######################################################

  ## Resque is the background processing sysem used by Diaspora
  ## Resque web is an admin tool for it. This settings decides wheter
  ## or not to inline it into Diaspora.
  mount_resque_web: true

  ## If you use Airbrake provide your API key here:
  airbrake_api_key: ''

  ## If you use NewRelic provide your credentials here:
  NEW_RELIC_LICENSE_KEY: ''
  new_relic_app_name: ''

######################################################
# Overrides
######################################################

development:
  <<: *defaults

production:
  <<: *defaults

##################################################
# FEDERATION LOGGER ##############################
# Do not touch unless you know what you're doing!#
##################################################

test:
  <<: *defaults
  pod_url: "http://localhost:9887/"
  socket_port: 8081

integration1:
  <<: *defaults
  pod_url: "http://localhost:3001/"

integration2:
  <<: *defaults
  pod_url: "http://localhost:3002/"