source "http://gems.github.com"
source "http://rubygems.org"

gemspec path: File.expand_path(File.dirname(__FILE__) + "/../")

# core
gem 'voluntary', github: 'volontariat/voluntary'

gem "rack-cors", "~> 0.2.4", require: "rack/cors"
gem "thin", "~> 1.3.1", require: false
gem "settingslogic", git: "https://github.com/binarylogic/settingslogic.git"
gem "acts_as_markup", git: "git://github.com/vigetlabs/acts_as_markup.git"
gem "auto_html", git: "git://github.com/Applicat/auto_html"
gem "recaptcha", require: "recaptcha/rails"
gem "will_paginate", github: "mislav/will_paginate"
gem "sinatra", require: false
gem "addressable", "~> 2.2", require: "addressable/uri"
gem "jasmine", git: "https://github.com/pivotal/jasmine-gem.git"

group :development do
  gem "mysql2", "~> 0.3.13"
  gem "linecache", "0.46", platforms: :mri_18
  gem "capistrano", "~> 2.15.5", require: false
  gem "capistrano_colors", "~> 0.5.5", require: false
  gem "capistrano-ext", "~> 1.2.1", require: false
  gem "yard", "~> 0.7", require: false
  gem 'better_errors', '~> 0.8.0'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'meta_request', '~> 0.2.8'
end

group :test do
  gem "cucumber-rails", "~> 1.3.0", require: false
  gem "rspec-instafail", "~> 0.2.4", require: false
  gem "webmock", "~> 1.8.11", require: false
  gem "simplecov", "~> 0.7.1", require: false
end

group :development, :test do
  gem "debugger", platforms: :mri_19
  gem "ruby-debug", "~> 0.10.4", platforms: :mri_18
end

group :assets do
  gem "therubyracer", "~> 0.12.0", platforms: :ruby
  gem "asset_sync", "~> 0.5.0", require: nil
end

group :production do
  gem "fastercsv", "~> 1.5.5", require: false
  gem "rack-ssl", "~> 1.3.3", require: "rack/ssl"
  gem "rack-rewrite", "~> 1.2.1", require: false
  gem "rack-google-analytics", "~> 0.11.0", require: "rack/google-analytics"
  gem "rack-piwik", "~> 0.1.3", require: false
end
